### ISSUE TITLE
Zapisy w dzienniku

### ISSUE THREAD

**Issue by Siemekk** [Outlander1210/G1_MOD_ER_PL_oficjalne#12]
Siemka ;) Gdy grałem fajną rzeczą było uporządkowanie wpisów po lewej stronie. Fajnie by było, gdy otrzymujemy wpis w zadaniu nie było tak:
"Nowy wpis w dzienniku"
Lecz tak :
"Nowy wpis w dzienniku"
"(Nazwa zadania)"
Mam spore pojęcie o skryptach, i można to łatwo osiągnąć dopisując tą linijkę do funkcji B_LogEntry (plik B_Functions.d) pod
PrintS_Ext		(NAME_NewLogEntry, COL_White);
Dodać to: 
PrintS(topic);

Jeżeli coś mi jeszcze przyjdzie, co może trochę pomóc graczowi to napiszę.

**Comment by Outlander1210** [comment]
Dzięki. Zrobione!

**Comment by Siemekk** [comment]
Sorki mały błąd xD
Nie ma nawiasów...
Powinno być tak:
PrintS(ConcatStrings("(",ConcatStrings(topic,")"));
